[package]
name = "TestFaucet"
version = "1.0.0"
authors = []

[addresses]
deployer = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
